### ISSUE TITLE
Repair - Repair parts page Epic

### ISSUE THREAD

**Issue by TheNando** [TheNando/crossed-wires-ui#1]
Stories:
 - [ ] List Robot parts
 - [ ] Show part damage
 - [ ] Show repair cost
 - [ ] API Repair action
 - [ ] Successful Repair notification
