### ISSUE TITLE
Augment - Install/Repair/Upgrade Epic

### ISSUE THREAD

**Issue by TheNando** [TheNando/crossed-wires-ui#2]
- [ ] Show robot parts
    - [ ] Show installed modules
    - [ ] Show available modules
    - [ ] Show part level (total upgrades)
    - [ ] Show if part is damaged (background color of part)
 - [ ] On part select:
    - [ ] If part is damaged, only show Repair option with cost
    - [ ] If a module is installed, show uninstall option
       - [ ] API: Uninstall part
    - [ ] If no module is installed, show Install option
       - [ ] Show list of acquired modules for that part
       - [ ] API: Install part
       - [ ] API: If part activated that turn, notify failed installation
    - [ ] Show Upgrade options
       - [ ] Show Upgrade tree options with cost
       - [ ] Options with unmet prerequisite are disabled
       - [ ] API: Install upgrade
 - [ ] Define list of upgrades
 - [ ] Notifications
