### ISSUE TITLE
Menu Epic

### ISSUE THREAD

**Issue by TheNando** [TheNando/crossed-wires-ui#3]
- [ ] Show icons on Menu option
 - [ ] Show active Menu options
 - [ ] Indicate percentage of people selecting option
 - [ ] Show Menu option basic help 
 - [ ] Show countdown bar
 - [ ] Change color on time up
