### ISSUE TITLE
Acquire - Store Epic

### ISSUE THREAD

**Issue by TheNando** [TheNando/crossed-wires-ui#4]
- [ ] Come up with list of Modules
 - [ ] Define Module schema
 - [ ] Show x random Modules for purchase
 - [ ] Show number of people selecting any given Module
 - [ ] The first person to request Module gets purchase
 - [ ] You can select another Module at any time
 - [ ] Supply and demand system?
    * items have a base cost that is a percentage of total money accumulated
    * Aggregate previous round purchases by facets:
       * Part (where it equips: arm, leg, or head)
       * Type (armor, weapon, utility, enhancement)
       * Tier (given quality of item)
    * Adjust Modifier cost for each facet based on if that facet was above or below average
       * ie, if most purchases were weapon type last turn, weapon modifier increases for next turn
