### ISSUE TITLE
Assess - Status Epic

### ISSUE THREAD

**Issue by TheNando** [TheNando/crossed-wires-ui#7]
- [ ] Show username and avatar 
 - [ ] Show overall score, color coded
 - [ ] Show robot and team name
 - [ ] Show total money
 - [ ] Show history of actions
 - [ ] Show history of notifications
