### ISSUE TITLE
Engage - Pilot Epic

### ISSUE THREAD

**Issue by TheNando** [TheNando/crossed-wires-ui#8]
- If ejected
    - [ ] show list of robot parts and occupancy
 - If piloting:
    - [ ] show robot part special menu
       * Head - map
       * Arms - punch or activate (equipped module action)
       * Leg - kick or activate (move forward, or turn)
    - [ ] Show part hit points/status
    - [ ] Show equipped module
    - [ ] Show eject
